# ============================================================================
# JustDefenders©
#
# File:
# C:\dev\justdefenders\frontend\tooling\validation\Test-PlatformApis.ps1
#
# Timestamp:
# 30 June 2026 09:45 Sydney
#
# Work Package:
# WP-003C
#
# Component:
# JustDefenders Engineering Toolkit
#
# Script:
# API Health Validator
#
# Purpose:
# Reads the platform inventory generated by the Platform Discovery Engine
# and validates the operational health of every discovered API endpoint.
#
# Version:
# 1.0.0
#
# Outputs:
#
#   tooling\output\platform-health.json
#   tooling\output\platform-health.csv
#   tooling\output\platform-health.md
#
# PowerShell:
# PowerShell 7+
#
# ============================================================================
#
# CHANGE LOG
#
# 30 June 2026
#
# Initial implementation.
#
# ============================================================================

Set-StrictMode -Version Latest

$ErrorActionPreference = "Stop"

# -----------------------------------------------------------------------------
# Resolve Project Paths
# -----------------------------------------------------------------------------

$ProjectRoot = Split-Path $PSScriptRoot -Parent
$ProjectRoot = Split-Path $ProjectRoot -Parent

$OutputFolder = Join-Path $ProjectRoot "tooling\output"

$InventoryFile = Join-Path `
    $OutputFolder `
    "platform-inventory.json"

# -----------------------------------------------------------------------------
# Platform Configuration
# -----------------------------------------------------------------------------

$BaseUrl = "http://localhost:8081"

# -----------------------------------------------------------------------------
# Platform Version
# -----------------------------------------------------------------------------

function Get-PlatformVersion
{
    $packageJson = Join-Path $ProjectRoot "package.json"

    if (Test-Path $packageJson)
    {
        try
        {
            $package = Get-Content `
                $packageJson `
                -Raw |
                ConvertFrom-Json

            if ($package.version)
            {
                return $package.version
            }
        }
        catch
        {
        }
    }

    return "Development"
}

$PlatformVersion = Get-PlatformVersion

$GeneratedAt = Get-Date

# -----------------------------------------------------------------------------
# Console Banner
# -----------------------------------------------------------------------------

function Write-Banner
{
    Write-Host ""
    Write-Host "============================================================"
    Write-Host " JustDefenders Engineering Toolkit"
    Write-Host " API Health Validator"
    Write-Host "============================================================"
    Write-Host ""

    Write-Host ("Project           : {0}" -f $ProjectRoot)
    Write-Host ("Platform Version  : {0}" -f $PlatformVersion)
    Write-Host ("Generated         : {0}" -f $GeneratedAt)
    Write-Host ("Base URL          : {0}" -f $BaseUrl)
    Write-Host ""
}

# -----------------------------------------------------------------------------
# Inventory Loader
# -----------------------------------------------------------------------------

function Read-Inventory
{
    Write-Host "Loading platform inventory..."
    Write-Host ""

    if (-not (Test-Path $InventoryFile))
    {
        throw "Platform inventory not found: $InventoryFile"
    }

    $inventory = Get-Content `
        $InventoryFile `
        -Raw |
        ConvertFrom-Json

    Write-Host ("Routes Loaded : {0}" -f $inventory.Count)
    Write-Host ""

    return $inventory
}

# -----------------------------------------------------------------------------
# API Validator
# -----------------------------------------------------------------------------

function Invoke-Api
{
    param(
        [Parameter(Mandatory)]
        [pscustomobject]$Api
    )

    $route = $Api.Route

#
# Determine which HTTP method to use.
# Version 1 only validates GET endpoints.
#

if (-not $Api.GET)
{
    return [PSCustomObject]@{

        Capability = $Api.Capability

        Route = $route

        Url = ""

        Method = "GET"

        StatusCode = 0

        Success = $false

        Healthy = "SKIPPED"

        Json = $false

        ResponseTimeMs = 0

        ResponseBytes = 0

        Error = "GET not implemented"

        TestedAt = Get-Date

    }
}

    #
    # Skip dynamic routes
    #
    if (
        $route -match "\[" `
        -or
        $route -match "\.\.\."
    )
    {
        return [PSCustomObject]@{

            Capability      = $Api.Capability

            Route           = $route

            Url             = ""

            StatusCode      = 0

            Success         = $false

            Healthy         = "SKIPPED"

            Json            = $false

            ResponseTimeMs  = 0

            ResponseBytes   = 0

            Error           = "Dynamic Route"

            TestedAt        = Get-Date

        }
    }

    $url = "$BaseUrl$route"

    $stopwatch = [System.Diagnostics.Stopwatch]::StartNew()

    try
    {
        $response = Invoke-WebRequest `
            -Uri $url `
            -Method GET `
            -UseBasicParsing `
            -TimeoutSec 15

        $stopwatch.Stop()

        $jsonValid = $false

        try
        {
            $null = $response.Content | ConvertFrom-Json

            $jsonValid = $true
        }
        catch
        {
        }

        return [PSCustomObject]@{

            Capability      = $Api.Capability

            Route           = $route

            Url             = $url

Method = "GET"

            StatusCode      = $response.StatusCode

            Success         = $true

            Healthy         = "YES"

            Json            = $jsonValid

            ResponseTimeMs  = $stopwatch.ElapsedMilliseconds

            ResponseBytes   = $response.RawContentLength

            Error           = ""

            TestedAt        = Get-Date

        }
    }
    catch
    {
        $stopwatch.Stop()

        return [PSCustomObject]@{

            Capability      = $Api.Capability

            Route           = $route

            Url             = $url

Method = "GET"

            StatusCode      = 0

            Success         = $false

            Healthy         = "NO"

            Json            = $false

            ResponseTimeMs  = $stopwatch.ElapsedMilliseconds

            ResponseBytes   = 0

            Error           = $_.Exception.Message

            TestedAt        = Get-Date

        }
    }
}

# -----------------------------------------------------------------------------
# Validate All Routes
# -----------------------------------------------------------------------------

function Test-AllRoutes
{
    param(
        [Parameter(Mandatory)]
        [array]$Inventory
    )

    Write-Host "Validating API routes..."
    Write-Host ""

    $results = @()

    $total = $Inventory.Count
    $current = 0

    foreach ($api in $Inventory)
    {
        $current++

        Write-Progress `
            -Activity "API Health Validation" `
            -Status "$current of $total" `
            -PercentComplete (($current / $total) * 100)

        $result = Invoke-Api -Api $api

        $results += $result

        $statusColour = switch ($result.Healthy)
        {
            "YES"     { "Green" }

            "NO"      { "Red" }

            "SKIPPED" { "Yellow" }

            default   { "White" }
        }

        Write-Host (
            "[{0}] {1}" -f
            $result.Healthy.PadRight(8),
            $result.Route
        ) -ForegroundColor $statusColour
    }

    Write-Progress `
        -Activity "API Health Validation" `
        -Completed

    Write-Host ""
    Write-Host ("Routes Tested : {0}" -f $results.Count)
    Write-Host ""

    return $results
}
# -----------------------------------------------------------------------------
# Build Health Summary
# -----------------------------------------------------------------------------

function Build-HealthSummary
{
    param(
        [Parameter(Mandatory)]
        [array]$Results
    )

    Write-Host "Building health summary..."
    Write-Host ""

    $healthy = @($Results | Where-Object Healthy -eq "YES").Count

    $failed = @($Results | Where-Object Healthy -eq "NO").Count

    $dynamicSkipped = @(
    $Results |
    Where-Object Error -eq "Dynamic Route"
).Count

$getSkipped = @(
    $Results |
    Where-Object Error -eq "GET not implemented"
).Count

$skipped = $dynamicSkipped + $getSkipped

    $tested = $healthy + $failed

    if ($tested -gt 0)
    {
        $overallHealth = [math]::Round(
            ($healthy / $tested) * 100,
            2
        )
    }
    else
    {
        $overallHealth = 0
    }

    $capabilitySummary = $Results |
        Group-Object Capability |
        Sort-Object Name |
        ForEach-Object {

            $capabilityResults = $_.Group

            $capHealthy = @(
                $capabilityResults |
                Where-Object Healthy -eq "YES"
            ).Count

            $capFailed = @(
                $capabilityResults |
                Where-Object Healthy -eq "NO"
            ).Count

            $capSkipped = @(
                $capabilityResults |
                Where-Object Healthy -eq "SKIPPED"
            ).Count

            $capTested = $capHealthy + $capFailed

            if ($capTested -gt 0)
            {
                $capHealth = [math]::Round(
                    ($capHealthy / $capTested) * 100,
                    2
                )
            }
            else
            {
                $capHealth = 0
            }

            [PSCustomObject]@{

                Capability = $_.Name

                Total = $capabilityResults.Count

                Healthy = $capHealthy

                Failed = $capFailed

                Skipped = $capSkipped

                HealthPercent = $capHealth

            }

        }

    Write-Host ("Healthy APIs         : {0}" -f $healthy)

Write-Host ("Failed APIs          : {0}" -f $failed)

Write-Host ("Dynamic Routes       : {0}" -f $dynamicSkipped)

Write-Host ("GET Not Implemented  : {0}" -f $getSkipped)

Write-Host ("Skipped Total        : {0}" -f $skipped)

Write-Host ("Overall Health       : {0}%" -f $overallHealth)
    Write-Host ""

    return [PSCustomObject]@{

    TotalRoutes = $Results.Count

    Healthy = $healthy

    Failed = $failed

    DynamicSkipped = $dynamicSkipped

    GetNotImplemented = $getSkipped

    Skipped = $skipped

    OverallHealth = $overallHealth

    CapabilitySummary = $capabilitySummary

}
}

# -----------------------------------------------------------------------------
# Export Health Results (JSON)
# -----------------------------------------------------------------------------

function Export-HealthJson
{
    param(
        [Parameter(Mandatory)]
        [array]$Results,

        [Parameter(Mandatory)]
        [pscustomobject]$Summary
    )

    Write-Host "Exporting health results (JSON)..."

    $jsonFile = Join-Path `
        $OutputFolder `
        "platform-health.json"

    $document = [PSCustomObject]@{

        PlatformVersion = $PlatformVersion

        Generated = $GeneratedAt.ToString("yyyy-MM-dd HH:mm:ss")

        BaseUrl = $BaseUrl

        Summary = $Summary

        Results = $Results

    }

    $document |
        ConvertTo-Json `
            -Depth 10 |
        Set-Content `
            -Path $jsonFile `
            -Encoding UTF8

    Write-Host ("JSON Export : {0}" -f $jsonFile)
    Write-Host ""

    return $jsonFile
}

# -----------------------------------------------------------------------------
# Export Health Results (CSV)
# -----------------------------------------------------------------------------

function Export-HealthCsv
{
    param(
        [Parameter(Mandatory)]
        [array]$Results
    )

    Write-Host "Exporting health results (CSV)..."

    $csvFile = Join-Path `
        $OutputFolder `
        "platform-health.csv"

    $Results |
    Sort-Object `
        Capability,
        Route |
    Select-Object `
        Capability,
        Route,
        Method,
        StatusCode,
        Healthy,
        Success,
        Json,
        ResponseTimeMs,
        ResponseBytes,
        Error,
        TestedAt |
    Export-Csv `
        -Path $csvFile `
        -NoTypeInformation `
        -Encoding UTF8

    Write-Host ("CSV Export : {0}" -f $csvFile)
    Write-Host ""

    return $csvFile
}

# -----------------------------------------------------------------------------
# Export Health Report (Markdown)
# -----------------------------------------------------------------------------

function Export-HealthMarkdown
{
    param(
        [Parameter(Mandatory)]
        [pscustomobject]$Summary,

        [Parameter(Mandatory)]
        [array]$Results
    )

    Write-Host "Exporting engineering report (Markdown)..."

    $reportFile = Join-Path `
        $OutputFolder `
        "platform-health.md"

    $report = @()

    $report += "# JustDefenders API Health Report"
    $report += ""
    $report += "**Platform Version:** $PlatformVersion"
    $report += ""
    $report += "**Generated:** $($GeneratedAt.ToString('yyyy-MM-dd HH:mm:ss'))"
    $report += ""
    $report += "**Base URL:** $BaseUrl"
    $report += ""
    $report += "**Total Routes:** $($Summary.TotalRoutes)"
    $report += ""
    $report += "**Healthy APIs:** $($Summary.Healthy)"
    $report += ""
    $report += "**Failed APIs:** $($Summary.Failed)"
    $report += ""
    $report += "**Skipped APIs:** $($Summary.Skipped)"
    $report += ""
    $report += "**Overall Health:** $($Summary.OverallHealth)%"
    $report += ""
    $report += "## Capability Health"
    $report += ""
    $report += "| Capability | Total | Healthy | Failed | Skipped | Health % |"
    $report += "|------------|------:|--------:|-------:|---------:|---------:|"

    foreach ($capability in $Summary.CapabilitySummary)
    {
        $report += "| $($capability.Capability) | $($capability.Total) | $($capability.Healthy) | $($capability.Failed) | $($capability.Skipped) | $($capability.HealthPercent) |"
    }

    $report += ""
    $report += "## Failed Endpoints"
    $report += ""

    $failed = $Results |
        Where-Object Healthy -eq "NO" |
        Sort-Object Capability, Route

    if ($failed.Count -eq 0)
    {
        $report += "No failed endpoints detected."
    }
    else
    {
        $report += "| Capability | Route | Status | Error |"
        $report += "|------------|-------|------:|-------|"

        foreach ($endpoint in $failed)
        {
            $error = $endpoint.Error -replace '\|', '/'

            $report += "| $($endpoint.Capability) | $($endpoint.Route) | $($endpoint.StatusCode) | $error |"
        }
    }

    $report |
        Set-Content `
            -Path $reportFile `
            -Encoding UTF8

    Write-Host ("Markdown Export : {0}" -f $reportFile)
    Write-Host ""

    return $reportFile
}

# -----------------------------------------------------------------------------
# Main Program
# -----------------------------------------------------------------------------

try
{
    $stopwatch = [System.Diagnostics.Stopwatch]::StartNew()

    Write-Banner

    $inventory = Read-Inventory

    $results = Test-AllRoutes `
        -Inventory $inventory

    $summary = Build-HealthSummary `
        -Results $results

    $jsonFile = Export-HealthJson `
        -Results $results `
        -Summary $summary

    $csvFile = Export-HealthCsv `
        -Results $results

    $markdownFile = Export-HealthMarkdown `
        -Summary $summary `
        -Results $results

    $stopwatch.Stop()

    Write-Host ""
    Write-Host "============================================================"
    Write-Host " Validation Complete"
    Write-Host "============================================================"
    Write-Host ""

    Write-Host ("Platform Version : {0}" -f $PlatformVersion)
    Write-Host ("Generated        : {0}" -f $GeneratedAt.ToString("yyyy-MM-dd HH:mm:ss"))
    Write-Host ""

    Write-Host ("Total Routes     : {0}" -f $summary.TotalRoutes)
    Write-Host ("Healthy APIs     : {0}" -f $summary.Healthy)
    Write-Host ("Failed APIs      : {0}" -f $summary.Failed)
    Write-Host ("Skipped APIs     : {0}" -f $summary.Skipped)
    Write-Host ("Overall Health   : {0}%" -f $summary.OverallHealth)
    Write-Host ""

    Write-Host ("Health JSON      : {0}" -f $jsonFile)
    Write-Host ("Health CSV       : {0}" -f $csvFile)
    Write-Host ("Health Markdown  : {0}" -f $markdownFile)
    Write-Host ""

    Write-Host ("Elapsed Time     : {0}" -f $stopwatch.Elapsed)

    Write-Host ""
    Write-Host "============================================================"
    Write-Host " JustDefenders Engineering Toolkit"
    Write-Host " API Health Validator Complete"
    Write-Host "============================================================"
    Write-Host ""
}
catch
{
    Write-Host ""
    Write-Host "============================================================"
    Write-Host " VALIDATION FAILED"
    Write-Host "============================================================"
    Write-Host ""

    Write-Host ("Error : {0}" -f $_.Exception.Message)

    Write-Host ""

    exit 1
}

