# ============================================================================
# JustDefenders©
#
# File:
# C:\dev\justdefenders\frontend\tooling\validation\Test-PlatformApis.ps1
#
# Timestamp:
# 11 August 2026 16:22 Sydney
#
# Work Package:
# WP-003E – Platform API Validation
#
# Component:
# JustDefenders Engineering Toolkit
#
# Script:
# Platform API Health Validator
#
# Purpose:
# Reads the platform inventory generated by the Platform Discovery Engine
# and validates the operational health of every discovered API endpoint
# using the HTTP methods represented by the inventory.
#
# Version:
# 2.0.0
#
# Engineering Baseline:
# WP003E_TEST_PLATFORM_APIS_V200
#
# Outputs:
#
#   tooling\output\platform-health.json
#   tooling\output\platform-health.csv
#   tooling\output\platform-health.md
#
# PowerShell:
# PowerShell 7+
#
# ============================================================================

Set-StrictMode -Version Latest

$ErrorActionPreference = "Stop"

# -----------------------------------------------------------------------------
# Resolve Project Paths
# -----------------------------------------------------------------------------

$ProjectRoot = Split-Path $PSScriptRoot -Parent
$ProjectRoot = Split-Path $ProjectRoot -Parent

$OutputFolder = Join-Path $ProjectRoot "tooling\output"

$InventoryFile = Join-Path `
    $OutputFolder `
    "platform-inventory.json"

# -----------------------------------------------------------------------------
# Platform Configuration
# -----------------------------------------------------------------------------

$BaseUrl = "http://localhost:8081"

# -----------------------------------------------------------------------------
# Platform Version
# -----------------------------------------------------------------------------

function Get-PlatformVersion
{
    $packageJson = Join-Path $ProjectRoot "package.json"

    if (Test-Path $packageJson)
    {
        try
        {
            $package = Get-Content `
                $packageJson `
                -Raw |
                ConvertFrom-Json

            if ($package.version)
            {
                return $package.version
            }
        }
        catch
        {
        }
    }

    return "Development"
}

$PlatformVersion = Get-PlatformVersion

$GeneratedAt = Get-Date

# -----------------------------------------------------------------------------
# Console Banner
# -----------------------------------------------------------------------------

function Write-Banner
{
    Write-Host ""
    Write-Host "============================================================"
    Write-Host " JustDefenders Engineering Toolkit"
    Write-Host " Platform API Health Validator v2"
    Write-Host "============================================================"
    Write-Host ""

    Write-Host ("Project           : {0}" -f $ProjectRoot)
    Write-Host ("Platform Version  : {0}" -f $PlatformVersion)
    Write-Host ("Validator Version : 2.0.0")
    Write-Host ("Engineering Base  : WP003E_TEST_PLATFORM_APIS_V200")
    Write-Host ("Generated         : {0}" -f $GeneratedAt)
    Write-Host ("Base URL          : {0}" -f $BaseUrl)
    Write-Host ""
}

# -----------------------------------------------------------------------------
# Inventory Loader
# -----------------------------------------------------------------------------

function Read-Inventory
{
    Write-Host "Loading platform inventory..."
    Write-Host ""

    if (-not (Test-Path $InventoryFile))
    {
        throw "Platform inventory not found: $InventoryFile"
    }

    $inventory = Get-Content `
        $InventoryFile `
        -Raw |
        ConvertFrom-Json

    if ($null -eq $inventory)
    {
        throw "Platform inventory is empty: $InventoryFile"
    }

    Write-Host ("Routes Loaded : {0}" -f @($inventory).Count)
    Write-Host ""

    return @($inventory)
}

# -----------------------------------------------------------------------------
# Inventory Property Helper
# -----------------------------------------------------------------------------

function Get-InventoryProperty
{
    param(
        [Parameter(Mandatory)]
        [pscustomobject]$Api,

        [Parameter(Mandatory)]
        [string]$Name
    )

    $property = $Api.PSObject.Properties[$Name]

    if ($null -eq $property)
    {
        return $null
    }

    return $property.Value
}

# -----------------------------------------------------------------------------
# Configured Request Headers / Authentication
# -----------------------------------------------------------------------------

function Get-ConfiguredHeaders
{
    param(
        [Parameter(Mandatory)]
        [pscustomobject]$Api
    )

    $headers = @{}

    $configuredHeaders = Get-InventoryProperty `
        -Api $Api `
        -Name "Headers"

    if ($null -ne $configuredHeaders)
    {
        if ($configuredHeaders -is [System.Collections.IDictionary])
        {
            foreach ($key in $configuredHeaders.Keys)
            {
                if ($null -ne $configuredHeaders[$key])
                {
                    $headers[[string]$key] = [string]$configuredHeaders[$key]
                }
            }
        }
        else
        {
            foreach ($property in $configuredHeaders.PSObject.Properties)
            {
                if ($null -ne $property.Value)
                {
                    $headers[$property.Name] = [string]$property.Value
                }
            }
        }
    }

    $authentication = Get-InventoryProperty `
        -Api $Api `
        -Name "Authentication"

    if ($null -ne $authentication)
    {
        $environmentVariable = Get-InventoryProperty `
            -Api $authentication `
            -Name "EnvironmentVariable"

        $headerName = Get-InventoryProperty `
            -Api $authentication `
            -Name "HeaderName"

        $scheme = Get-InventoryProperty `
            -Api $authentication `
            -Name "Scheme"

        if (
            $environmentVariable `
            -and
            $headerName
        )
        {
            $token = [Environment]::GetEnvironmentVariable(
                [string]$environmentVariable
            )

            if (-not [string]::IsNullOrWhiteSpace($token))
            {
                if ($scheme)
                {
                    $headers[[string]$headerName] =
                        "{0} {1}" -f $scheme, $token
                }
                else
                {
                    $headers[[string]$headerName] = $token
                }
            }
        }
    }

    return $headers
}

# -----------------------------------------------------------------------------
# HTTP Method Discovery
# -----------------------------------------------------------------------------

function Get-ApiMethods
{
    param(
        [Parameter(Mandatory)]
        [pscustomobject]$Api
    )

    $supportedMethods = @(
        "GET",
        "POST",
        "PUT",
        "DELETE"
    )

    $inventoryMethods = $Api.Methods

    if ($null -eq $inventoryMethods)
    {
        return @()
    }

    $supported = @()

    foreach ($methodValue in @($inventoryMethods))
    {
        if ($null -eq $methodValue)
        {
            continue
        }

        $methodTokens = ([string]$methodValue).Split(
            ',',
            [System.StringSplitOptions]::RemoveEmptyEntries
        )

        foreach ($methodToken in $methodTokens)
        {
            $method = $methodToken.Trim().ToUpperInvariant()

            if (
                -not [string]::IsNullOrWhiteSpace($method) `
                -and
                $method -in $supportedMethods `
                -and
                $method -notin $supported
            )
            {
                $supported += $method
            }
        }
    }

    return @($supported)
}

# -----------------------------------------------------------------------------
# HTTP Response Status Extraction
# -----------------------------------------------------------------------------

function Get-ResponseStatusCode
{
    param(
        [Parameter(Mandatory)]
        $Response
    )

    $statusProperty = $Response.PSObject.Properties["StatusCode"]

    if ($null -eq $statusProperty)
    {
        return 0
    }

    try
    {
        return [int]$statusProperty.Value
    }
    catch
    {
        return 0
    }
}

# -----------------------------------------------------------------------------
# HTTP Error Status Extraction
# -----------------------------------------------------------------------------

function Get-ErrorStatusCode
{
    param(
        [Parameter(Mandatory)]
        [System.Management.Automation.ErrorRecord]$ErrorRecord
    )

    $exception = $ErrorRecord.Exception

    if ($null -eq $exception)
    {
        return 0
    }

    $responseProperty = $exception.PSObject.Properties["Response"]

    if ($null -eq $responseProperty)
    {
        return 0
    }

    $response = $responseProperty.Value

    if ($null -eq $response)
    {
        return 0
    }

    $statusProperty = $response.PSObject.Properties["StatusCode"]

    if ($null -ne $statusProperty)
    {
        try
        {
            $value = $statusProperty.Value

            if ($value -is [int])
            {
                return [int]$value
            }

            if ($value.PSObject.Properties["value__"])
            {
                return [int]$value.value__
            }

            return [int]$value
        }
        catch
        {
        }
    }

    return 0
}

# -----------------------------------------------------------------------------
# API Validator
# -----------------------------------------------------------------------------

function Invoke-Api
{
    param(
        [Parameter(Mandatory)]
        [pscustomobject]$Api
    )

    $route = [string]$Api.Route

    #
    # Skip dynamic routes before request construction.
    #
    if (
        $route -match "\[" `
        -or
        $route -match "\.\.\."
    )
    {
        return @(
            [PSCustomObject]@{

                Capability      = $Api.Capability

                Route           = $route

                Url             = ""

                Method          = "SKIPPED"

                StatusCode      = 0

                Success         = $false

                Healthy         = "SKIPPED"

                Json            = $false

                ResponseTimeMs  = 0

                ResponseBytes   = 0

                Error           = "Dynamic Route"

                TestedAt        = Get-Date

            }
        )
    }

    $methods = @(Get-ApiMethods -Api $Api)

    if ($methods.Count -eq 0)
    {
        return @(
            [PSCustomObject]@{

                Capability      = $Api.Capability

                Route           = $route

                Url             = ""

                Method          = "NONE"

                StatusCode      = 0

                Success         = $false

                Healthy         = "SKIPPED"

                Json            = $false

                ResponseTimeMs  = 0

                ResponseBytes   = 0

                Error           = "No supported HTTP method represented by inventory"

                TestedAt        = Get-Date

            }
        )
    }

    $url = "$BaseUrl$route"

    $headers = Get-ConfiguredHeaders -Api $Api

    $body = Get-InventoryProperty `
        -Api $Api `
        -Name "Body"

    $results = @()

    foreach ($method in $methods)
    {
        $stopwatch = [System.Diagnostics.Stopwatch]::StartNew()

        try
        {
            $requestParameters = @{
                Uri             = $url
                Method          = $method
                Headers         = $headers
                UseBasicParsing = $true
                TimeoutSec      = 15
                ErrorAction     = "Stop"
            }

            if (
                $method -in @("POST", "PUT") `
                -and
                $null -ne $body
            )
            {
                if (
                    $body -is [string] `
                    -or
                    $body -is [byte[]]
                )
                {
                    $requestParameters["Body"] = $body
                }
                else
                {
                    $requestParameters["Body"] =
                        $body | ConvertTo-Json -Depth 10
                }
            }

            $response = Invoke-WebRequest @requestParameters

            $stopwatch.Stop()

            $statusCode = Get-ResponseStatusCode `
                -Response $response

            $healthy = (
                $statusCode -ge 200 `
                -and
                $statusCode -lt 300
            )

            $jsonValid = $false

            if (
                $null -ne $response.Content `
                -and
                -not [string]::IsNullOrWhiteSpace(
                    [string]$response.Content
                )
            )
            {
                try
                {
                    $null = $response.Content | ConvertFrom-Json

                    $jsonValid = $true
                }
                catch
                {
                }
            }

            $responseBytes = 0

            if ($null -ne $response.RawContentLength)
            {
                try
                {
                    $responseBytes = [int]$response.RawContentLength
                }
                catch
                {
                    $responseBytes = 0
                }
            }

            $results += [PSCustomObject]@{

                Capability      = $Api.Capability

                Route           = $route

                Url             = $url

                Method          = $method

                StatusCode      = $statusCode

                Success         = $healthy

                Healthy         = if ($healthy) { "YES" } else { "NO" }

                Json            = $jsonValid

                ResponseTimeMs  = $stopwatch.ElapsedMilliseconds

                ResponseBytes   = $responseBytes

                Error           = if ($healthy) {
                    ""
                }
                else {
                    "HTTP status $statusCode"
                }

                TestedAt        = Get-Date

            }
        }
        catch
        {
            $stopwatch.Stop()

            $statusCode = Get-ErrorStatusCode `
                -ErrorRecord $_

            $results += [PSCustomObject]@{

                Capability      = $Api.Capability

                Route           = $route

                Url             = $url

                Method          = $method

                StatusCode      = $statusCode

                Success         = $false

                Healthy         = "NO"

                Json            = $false

                ResponseTimeMs  = $stopwatch.ElapsedMilliseconds

                ResponseBytes   = 0

                Error           = $_.Exception.Message

                TestedAt        = Get-Date

            }
        }
    }

    return @($results)
}

# -----------------------------------------------------------------------------
# Validate All Routes
# -----------------------------------------------------------------------------

function Test-AllRoutes
{
    param(
        [Parameter(Mandatory)]
        [array]$Inventory
    )

    Write-Host "Validating API routes..."
    Write-Host ""

    $results = @()

    $total = $Inventory.Count
    $current = 0

    foreach ($api in $Inventory)
    {
        $current++

        Write-Progress `
            -Activity "API Health Validation" `
            -Status "$current of $total" `
            -PercentComplete (($current / $total) * 100)

        $routeResults = @(Invoke-Api -Api $api)

        foreach ($result in $routeResults)
        {
            $results += $result

            $statusColour = switch ($result.Healthy)
            {
                "YES"     { "Green" }

                "NO"      { "Red" }

                "SKIPPED" { "Yellow" }

                default   { "White" }
            }

            Write-Host (
                "[{0}] {1} {2}" -f
                $result.Healthy.PadRight(8),
                $result.Method.PadRight(7),
                $result.Route
            ) -ForegroundColor $statusColour
        }
    }

    Write-Progress `
        -Activity "API Health Validation" `
        -Completed

    Write-Host ""
    Write-Host ("Validation Results : {0}" -f $results.Count)
    Write-Host ""

    return @($results)
}

# -----------------------------------------------------------------------------
# Build Health Summary
# -----------------------------------------------------------------------------

function Build-HealthSummary
{
    param(
        [Parameter(Mandatory)]
        [array]$Results
    )

    Write-Host "Building health summary..."
    Write-Host ""

    $healthy = @(
        $Results |
        Where-Object Healthy -eq "YES"
    ).Count

    $failed = @(
        $Results |
        Where-Object Healthy -eq "NO"
    ).Count

    $dynamicSkipped = @(
        $Results |
        Where-Object Error -eq "Dynamic Route"
    ).Count

    $methodSkipped = @(
        $Results |
        Where-Object {
            $_.Healthy -eq "SKIPPED" `
            -and
            $_.Error -ne "Dynamic Route"
        }
    ).Count

    $skipped = @(
        $Results |
        Where-Object Healthy -eq "SKIPPED"
    ).Count

    $tested = $healthy + $failed

    if ($tested -gt 0)
    {
        $overallHealth = [math]::Round(
            ($healthy / $tested) * 100,
            2
        )
    }
    else
    {
        $overallHealth = 0
    }

    $capabilitySummary = $Results |
        Group-Object Capability |
        Sort-Object Name |
        ForEach-Object {

            $capabilityResults = $_.Group

            $capHealthy = @(
                $capabilityResults |
                Where-Object Healthy -eq "YES"
            ).Count

            $capFailed = @(
                $capabilityResults |
                Where-Object Healthy -eq "NO"
            ).Count

            $capSkipped = @(
                $capabilityResults |
                Where-Object Healthy -eq "SKIPPED"
            ).Count

            $capTested = $capHealthy + $capFailed

            if ($capTested -gt 0)
            {
                $capHealth = [math]::Round(
                    ($capHealthy / $capTested) * 100,
                    2
                )
            }
            else
            {
                $capHealth = 0
            }

            [PSCustomObject]@{

                Capability = $_.Name

                Total = $capabilityResults.Count

                Healthy = $capHealthy

                Failed = $capFailed

                Skipped = $capSkipped

                HealthPercent = $capHealth

            }
        }

    Write-Host ("Healthy APIs         : {0}" -f $healthy)
    Write-Host ("Failed APIs          : {0}" -f $failed)
    Write-Host ("Dynamic Routes       : {0}" -f $dynamicSkipped)
    Write-Host ("Method Skipped       : {0}" -f $methodSkipped)
    Write-Host ("Skipped Total        : {0}" -f $skipped)
    Write-Host ("Overall Health       : {0}%" -f $overallHealth)
    Write-Host ""

    return [PSCustomObject]@{

        TotalRoutes = $Results.Count

        Healthy = $healthy

        Failed = $failed

        DynamicSkipped = $dynamicSkipped

        GetNotImplemented = $methodSkipped

        Skipped = $skipped

        OverallHealth = $overallHealth

        CapabilitySummary = $capabilitySummary

    }
}

# -----------------------------------------------------------------------------
# Export Health Results (JSON)
# -----------------------------------------------------------------------------

function Export-HealthJson
{
    param(
        [Parameter(Mandatory)]
        [array]$Results,

        [Parameter(Mandatory)]
        [pscustomobject]$Summary
    )

    Write-Host "Exporting health results (JSON)..."

    if (-not (Test-Path $OutputFolder))
    {
        New-Item `
            -Path $OutputFolder `
            -ItemType Directory `
            -Force |
            Out-Null
    }

    $jsonFile = Join-Path `
        $OutputFolder `
        "platform-health.json"

    $document = [PSCustomObject]@{

        ValidatorVersion = "2.0.0"

        EngineeringBaseline = "WP003E_TEST_PLATFORM_APIS_V200"

        PlatformVersion = $PlatformVersion

        Generated = $GeneratedAt.ToString("yyyy-MM-dd HH:mm:ss")

        BaseUrl = $BaseUrl

        Summary = $Summary

        Results = $Results

    }

    $document |
        ConvertTo-Json `
            -Depth 10 |
        Set-Content `
            -Path $jsonFile `
            -Encoding UTF8

    Write-Host ("JSON Export : {0}" -f $jsonFile)
    Write-Host ""

    return $jsonFile
}

# -----------------------------------------------------------------------------
# Export Health Results (CSV)
# -----------------------------------------------------------------------------

function Export-HealthCsv
{
    param(
        [Parameter(Mandatory)]
        [array]$Results
    )

    Write-Host "Exporting health results (CSV)..."

    if (-not (Test-Path $OutputFolder))
    {
        New-Item `
            -Path $OutputFolder `
            -ItemType Directory `
            -Force |
            Out-Null
    }

    $csvFile = Join-Path `
        $OutputFolder `
        "platform-health.csv"

    $Results |
        Sort-Object `
            Capability,
            Route,
            Method |
        Select-Object `
            Capability,
            Route,
            Method,
            StatusCode,
            Healthy,
            Success,
            Json,
            ResponseTimeMs,
            ResponseBytes,
            Error,
            TestedAt |
        Export-Csv `
            -Path $csvFile `
            -NoTypeInformation `
            -Encoding UTF8

    Write-Host ("CSV Export : {0}" -f $csvFile)
    Write-Host ""

    return $csvFile
}

# -----------------------------------------------------------------------------
# Export Health Report (Markdown)
# -----------------------------------------------------------------------------

function Export-HealthMarkdown
{
    param(
        [Parameter(Mandatory)]
        [pscustomobject]$Summary,

        [Parameter(Mandatory)]
        [array]$Results
    )

    Write-Host "Exporting engineering report (Markdown)..."

    if (-not (Test-Path $OutputFolder))
    {
        New-Item `
            -Path $OutputFolder `
            -ItemType Directory `
            -Force |
            Out-Null
    }

    $reportFile = Join-Path `
        $OutputFolder `
        "platform-health.md"

    $report = @()

    $report += "# JustDefenders API Health Report"
    $report += ""
    $report += "**Validator Version:** 2.0.0"
    $report += ""
    $report += "**Engineering Baseline:** WP003E_TEST_PLATFORM_APIS_V200"
    $report += ""
    $report += "**Platform Version:** $PlatformVersion"
    $report += ""
    $report += "**Generated:** $($GeneratedAt.ToString('yyyy-MM-dd HH:mm:ss'))"
    $report += ""
    $report += "**Base URL:** $BaseUrl"
    $report += ""
    $report += "**Total Results:** $($Summary.TotalRoutes)"
    $report += ""
    $report += "**Healthy APIs:** $($Summary.Healthy)"
    $report += ""
    $report += "**Failed APIs:** $($Summary.Failed)"
    $report += ""
    $report += "**Skipped APIs:** $($Summary.Skipped)"
    $report += ""
    $report += "**Overall Health:** $($Summary.OverallHealth)%"
    $report += ""
    $report += "## Capability Health"
    $report += ""
    $report += "| Capability | Total | Healthy | Failed | Skipped | Health % |"
    $report += "|------------|------:|--------:|-------:|---------:|---------:|"

    foreach ($capability in $Summary.CapabilitySummary)
    {
        $report += "| $($capability.Capability) | $($capability.Total) | $($capability.Healthy) | $($capability.Failed) | $($capability.Skipped) | $($capability.HealthPercent) |"
    }

    $report += ""
    $report += "## Failed Endpoints"
    $report += ""

    $failed = @(
        $Results |
        Where-Object Healthy -eq "NO" |
        Sort-Object Capability, Route, Method
    )

    if ($failed.Count -eq 0)
    {
        $report += "No failed endpoints detected."
    }
    else
    {
        $report += "| Capability | Route | Method | Status | Error |"
        $report += "|------------|-------|--------|------:|-------|"

        foreach ($endpoint in $failed)
        {
            $error = [string]$endpoint.Error -replace '\|', '/'

            $report += "| $($endpoint.Capability) | $($endpoint.Route) | $($endpoint.Method) | $($endpoint.StatusCode) | $error |"
        }
    }

    $report |
        Set-Content `
            -Path $reportFile `
            -Encoding UTF8

    Write-Host ("Markdown Export : {0}" -f $reportFile)
    Write-Host ""

    return $reportFile
}

# -----------------------------------------------------------------------------
# Main Program
# -----------------------------------------------------------------------------

try
{
    $stopwatch = [System.Diagnostics.Stopwatch]::StartNew()

    Write-Banner

    $inventory = Read-Inventory

    $results = Test-AllRoutes `
        -Inventory $inventory

    $summary = Build-HealthSummary `
        -Results $results

    $jsonFile = Export-HealthJson `
        -Results $results `
        -Summary $summary

    $csvFile = Export-HealthCsv `
        -Results $results

    $markdownFile = Export-HealthMarkdown `
        -Summary $summary `
        -Results $results

    $stopwatch.Stop()

    Write-Host ""
    Write-Host "============================================================"
    Write-Host " Validation Complete"
    Write-Host "============================================================"
    Write-Host ""

    Write-Host ("Validator Version: {0}" -f "2.0.0")
    Write-Host ("Platform Version  : {0}" -f $PlatformVersion)
    Write-Host ("Generated         : {0}" -f $GeneratedAt.ToString("yyyy-MM-dd HH:mm:ss"))
    Write-Host ""

    Write-Host ("Total Results     : {0}" -f $summary.TotalRoutes)
    Write-Host ("Healthy APIs      : {0}" -f $summary.Healthy)
    Write-Host ("Failed APIs       : {0}" -f $summary.Failed)
    Write-Host ("Skipped APIs      : {0}" -f $summary.Skipped)
    Write-Host ("Overall Health    : {0}%" -f $summary.OverallHealth)
    Write-Host ""

    Write-Host ("Health JSON       : {0}" -f $jsonFile)
    Write-Host ("Health CSV        : {0}" -f $csvFile)
    Write-Host ("Health Markdown   : {0}" -f $markdownFile)
    Write-Host ""

    Write-Host ("Elapsed Time      : {0}" -f $stopwatch.Elapsed)

    Write-Host ""
    Write-Host "============================================================"
    Write-Host " JustDefenders Engineering Toolkit"
    Write-Host " Platform API Health Validator Complete"
    Write-Host "============================================================"
    Write-Host ""
}
catch
{
    Write-Host ""
    Write-Host "============================================================"
    Write-Host " VALIDATION FAILED"
    Write-Host "============================================================"
    Write-Host ""

    Write-Host ("Error : {0}" -f $_.Exception.Message)

    Write-Host ""

    exit 1
}
