version: "3.9"

services:

  prometheus:

    image: prom/prometheus

    container_name: jd-prometheus

    ports:
      - "9090:9090"

    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:

    image: grafana/grafana

    container_name: jd-grafana

    ports:
      - "3001:3000"

    environment:
      - GF_SECURITY_ADMIN_PASSWORD=justdefenders

  loki:

    image: grafana/loki:latest

    container_name: jd-loki

    ports:
      - "3100:3100"

    command:
      - -config.file=/etc/loki/local-config.yaml

  tempo:

    image: grafana/tempo:latest

    container_name: jd-tempo

    ports:
      - "3200:3200"
      - "4318:4318"

    command:
      - -config.file=/etc/tempo.yaml