#
# =====================================================
# JustDefenders ©
# File: C:\dev\justdefenders\frontend\tooling\engineering\Services\Public\Get-JDManagedServiceEngineMetadata.ps1
# Work Package: PR-005A.1 – Managed Service Engine Bootstrap
# Timestamp: 19 July 2026, 17:00
# =====================================================

function Get-JDManagedServiceEngineMetadata
{
    <#
        .SYNOPSIS
        Returns metadata for the JustDefenders Managed Service Engine.

        .DESCRIPTION
        Exposes immutable runtime metadata generated by the composition
        root. This function is intended for diagnostics, validation and
        engineering tooling.
    #>

    [CmdletBinding()]
    param()

    if ($null -eq $script:ManagedServiceEngineMetadata)
    {
        return [PSCustomObject]@{
            Name      = 'JustDefenders Managed Service Engine'
            Status    = 'NotLoaded'
            Timestamp = Get-Date
        }
    }

    return $script:ManagedServiceEngineMetadata
}
