apiVersion: v1
kind: Service

metadata:

  name: justdefenders-service

spec:

  selector:

    app: justdefenders

  ports:

  - protocol: TCP

    port: 80

    targetPort: 8081

  type: LoadBalancer