// =====================================================
// JustDefenders Â©
// File: C:\dev\justdefenders\frontend\app\api\garage\calendar\route.ts
// Timestamp: 2026-05-04 23:50
// Purpose: Generate ICS calendar event (Google + iOS)
// =====================================================

import { NextResponse } from "next/server"

export async function GET(req: Request){

  const { searchParams } = new URL(req.url)

  const vehicle = searchParams.get("vehicle") || "Vehicle"
  const part = searchParams.get("part") || "Maintenance"
  const date = searchParams.get("date") || new Date().toISOString()

  const dt = new Date(date)
    .toISOString()
    .replace(/[-:]/g,"")
    .split(".")[0] + "Z"

  const ics = `BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//JustDefenders//Vehicle Intelligence//EN
BEGIN:VEVENT
UID:${Date.now()}@justdefenders
DTSTAMP:${dt}
SUMMARY:${vehicle} - ${part}
DESCRIPTION:Maintenance reminder generated by JustDefenders
DTSTART:${dt}
DTEND:${dt}
END:VEVENT
END:VCALENDAR`

  return new Response(ics, {
    headers: {
      "Content-Type": "text/calendar",
      "Content-Disposition": "attachment; filename=maintenance.ics"
    }
  })
}